name: CI/CD

on:
  push:
    branches:
      - develop
      - feature/*
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: Build and push Docker image
      run: |
        docker build -t your-dockerhub-username/your-image-name .
        echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u your-dockerhub-username --password-stdin
        docker push your-dockerhub-username/your-image-name